config/routes.rb
PhotoStream::Application.routes.draw do
  #root 'sessions#new'
  root 'sessions#index'

  #defining some routes:
  get '/users', to: 'users#index', as: 'users'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/upload/:event_id', to: 'photos#new', as: 'upload'
  post '/upload/:event_id', to: 'photos#create', as: 'create_upload'

  resources :events do
    resources :photos
  end
  
  resources :users, :sessions

end

# match "/stream/:id", to: "photos#index", via: 'get'
# match "/addphoto/:id", to: "photos#new", via: 'get'

app/models/event.rb
# Good job here too.  I'm really happy to see that you have TODOs
# for yourself to look into later.

class Event < ActiveRecord::Base


  validates :name, presence: true, uniqueness: true
  validates :event_date, presence: true
  validates :user_id, presence: true
  # validates_uniqueness_of :

  # TODO: fix date validation and rspec

  # TODO: look into how uniqueness works. Uniqueness should only apply to both name and date. You should be able to have multiple events on one date and muliple events with the same name on different dates. Look up scope validation

  has_many :photos
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  before_filter :signed_in_user
  before_filter :check_event_owner, only: [:edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def create
    event = current_user.events.create event_params
  
    if event.save
      ## To ensure you don't make any mistakes, it would be good to use the
      ## path helper methods.  In this case, you are redirecting to events_path
      redirect_to '/events'
    else
      flash[:error] = "That event name already exits. Please enter a unique name."
      ## Use event helpers, new_event_path
      redirect_to '/events/new'
    end
  end

  def index
    @events = current_user.events 
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    event = Event.find(params[:id])
    event.delete
    ## Make sure to use helpers, events_path
    redirect_to '/events'
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update_attributes event_params
    redirect_to(event)
  end

  private
    def event_params
      params.require(:event).permit(:name, :event_date, :user_id)
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def check_event_owner
    ## Unfortunately this a small error that lead to a larger problem.
    ## The code you wrote will always return an array of results, so event
    ## will never be nil.  Therefore, this app does not do any authorization.
    ## params[:id] returns a string, and then you call
    ## first on that string which gets the first character of the string.
    ## For example:
    ##
    ## "abcdefg".first # returns a string "a"
    ##
    ## I think the code you wanted to have was the following:
    ##
    ## event = current_user.events.where(:id => params[:id]).first
    ## 
    event = current_user.events.where(:id => params[:id]).first
    if event.nil?
      flash[:error] = "Somthing is wrong. That's not your event."
      redirect_to events_path
    end
  end

end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for @event do |f| %>

	<%= label_tag :name, "Event Name" %>
	<%= f.text_field :name %>
	<%= label_tag :event_date, "Event Date" %>
	<%= f.date_select :event_date %>

	<%= f.submit "Update Event" %>

<% end %>

app/views/events/index.html.erb
<div class="row">
	<h1>Event Index</h1>

	<div class="table-responsive">
		<table class="table table-hover">
			<tr>
				<th>Event Name</th>
				<th>Date</th>
			<!-- 	<th>PhotoStream</th> -->
				<th>Photos</th>
			</tr>

			<% @events.each do |event| %>
				<tr>
					<td><%= link_to event.name, event_path(event.id) %></td>
					<td><%= event.event_date.to_s %></td>
					<!-- The link_to will still happen even if this is commented out.  Erb doesn't get commented out that easily.  I don't think it affects your code, but just something to be aware of. -->
					<!-- <td><%= link_to "/upload/#{event.id}", event_photos_path(event.id)%></td><br> -->
					<td><%= event.photos.count %></td>
					
				</tr>
			<% end %>
		</table>
	</div>

	<%= link_to "New Event", new_event_path, class: "btn btn-primary btn-sm"%>
</div>

app/views/events/new.html.erb
<h1>Photo Stream New Event</h1>

<%= form_for @event do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control"%><br>
	<%= f.label :event_date %>
	<%= f.date_select :event_date, class: "form-control"%>
	<%= f.submit %>

<% end %>

<%= link_to "Event Index", events_path, class: "btn btn-primary btn-sm newEvent" %>

app/views/events/show.html.erb
<h1><%= @event.name %><%= link_to 'Stream Photos', event_photos_path(@event), class: "btn btn-success btn-lg stream" %></h1><br>

<p> EVENT DATE: <%= @event.event_date %> </p>
<p><strong> PHOTOS: <%= @event.photos.empty? ? "empty": @event.photos.length %></strong></p>



<!-- adding a shortened url for uploading photos -->
<h3> Photo Upload link: 
<%= link_to "/upload/#{@event.id}", upload_path(@event), class: "btn btn-primary btn-sm" %></h3><br>

<a href="mailto:?subject=Use this link to upload photos&body=LINK: <%=upload_url(@event)%>", class="btn btn-warning btn-xs email">Email Link</a>

<%= link_to 'Edit', edit_event_path(@event), class: "btn btn-warning btn-xs edit" %>

<%= link_to @event, :method => :delete, :confirm => 'Are you sure?', :class=> "btn btn-danger btn-xs delete" do%>
			<span class="glyphicon glyphicon-trash"></span>

      <!-- WHAT OUT FOR SPACING HERE -->
			<% end %>




<!-- TODO: add a line that tells you when the last photo was added (photoStream last updated at: XXX) -->