config/routes.rb
PhotoStream::Application.routes.draw do
  #root 'sessions#new'
  root 'sessions#index'

  #defining some routes:
  get '/users', to: 'users#index', as: 'users'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/upload/:event_id', to: 'photos#new', as: 'upload'
  post '/upload/:event_id', to: 'photos#create', as: 'create_upload'

  resources :events do
    resources :photos
  end
  
  resources :users, :sessions

end

# match "/stream/:id", to: "photos#index", via: 'get'
# match "/addphoto/:id", to: "photos#new", via: 'get'

app/views/layouts/_header.html.erb
<!-- for nav bar -->

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PhotoStream</a>
    </div>

    <div class="collapse navbar-collapse" id="bar">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
        <li class="active"><%= link_to "My Events", events_path %></li>
        <% end %>
      </ul>
          <ul class="nav navbar-nav navbar-right">
            
              <% if signed_in? %>
                <li>
                <%= link_to "#{current_user.name}", current_user %>
                </li>
                <li>
                <%= link_to "Not you? Sign out", signout_path, method: "delete" %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Sign up", signup_path %>
                </li>
                <li>
                  <%= link_to "Sign in", signin_path %>
                </li>
              <% end %>
            
          </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoStream</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <%= include_gon %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag controller_name, "data-turbolinks-track" => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Good use of partials -->
	<%= render 'layouts/header' %>
	<div class="container">

		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-12 ">
					<% flash.each do |key, value| %>
						<div class="alert alert-<%=key%>"><%=value%></div>
					<% end %>	
					<%= yield %>
				</div>
	    </div>
	  </div>
  </div>

</body>
</html>